{% set name = "pyodc" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ecmwf/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6add7cf99b0cac68b6a83fb1b809910559b40b81d1415d090d7f4718e4098820

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cffi
    - pandas

test:
  imports:
    - pyodc
  requires:
    - pip
    - pytest
    - odc  # [not win]
  source_files:
    - CHANGELOG.md
    - codc
    - tests
    - pyodc
    - README.md
    - setup.py
  commands:
    - pip check
    - ODC_DIR=$PREFIX python -c "import codc"  # [not win]
    - ODC_DIR=$PREFIX python -m pytest  # [not win]

about:
  home: https://pypi.org/project/pyodc/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python interface to odc for encoding/decoding ODB-2 files
  description: |
    The package contains two different implementations of the same library:

    * pyodc is a pure-python encoder and decoder for ODB-2 data, which encodes
      data from, and decodes it into pandas data frames
    * codc is an implementation of the same API as pyodc that depends on the
      ECMWF odc library, and comes with _much_ better performance
  doc_url: https://pyodc.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/pyodc

extra:
  recipe-maintainers:
    - simondsmart
    - dvuckovic
